name = "lean-sail"
defaultTargets = ["Sail", "SailTest"]

[[require]]
name = "cslib"
scope = "leanprover"
rev = "main"

[[lean_lib]]
name = "Sail"
globs = ["Sail.**"]
leanOptions.weak.linter.style.nameCheck = false

[[lean_lib]]
name = "SailTest"
globs = ["SailTest.**"]
leanOptions.weak.linter.style.nameCheck = false
